// <auto-generated />
namespace Ecommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RoleFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202305250839574_RoleFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
